qlib_init:
    provider_uri: "~/Downloads/qlib_bin"
    region: cn
market: &market csi1000
benchmark: &benchmark SH000852
data_handler_config: &data_handler_config
    start_time: 2016-01-01
    end_time: 2025-08-06
    fit_start_time: 2016-01-01
    fit_end_time: 2023-09-30
    instruments: *market
    infer_processors:
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
        - class: Fillna
          kwargs:
              fields_group: feature
    learn_processors:
        - class: DropnaLabel
        - class: CSRankNorm
          kwargs:
              fields_group: label
    label: ["Ref($close, -5) / Ref($close, -1) - 1"] 
market_data_handler_config: &market_data_handler_config
    start_time: 2016-01-01
    end_time: 2025-08-06
    fit_start_time: 2016-01-01
    fit_end_time: 2023-09-30
    instruments: *market
    infer_processors:
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
        - class: Fillna
          kwargs:
              fields_group: feature
port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal: <PRED>
            topk: 30
            n_drop: 30
    backtest:
        start_time: 2024-01-01
        end_time: 2025-08-06
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            deal_price: close
task:
    model:
        class: MASTERModel
        module_path: qlib.contrib.model.pytorch_master_ts
        kwargs:
            seed: 0
            n_epochs: 40
            lr: 0.000008
            train_stop_loss_thred: 0.95
            market: *market
            benchmark: *benchmark
            save_prefix: *market
    dataset:
        class: MASTERTSDatasetH
        module_path: qlib.contrib.data.dataset
        kwargs:
            handler:
                class: Alpha158
                module_path: qlib.contrib.data.handler
                kwargs: *data_handler_config
            segments:
                train: [2016-01-01, 2023-09-30]
                valid: [2023-10-01, 2023-12-31]
                test: [2024-01-01, 2025-08-06]
            step_len: 8
            market_data_handler_config: *market_data_handler_config
    record: 
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            config: *port_analysis_config
