qlib_init:
    provider_uri: "~/Downloads/qlib_bin"
    region: cn
market: &market {{universe}}
benchmark: &benchmark SH000906

train_date_start: &train_date_start 2015-01-01
train_date_end: &train_date_end 2023-12-31
valid_date_start: &valid_date_start 2024-01-01
valid_date_end: &valid_date_end 2024-12-31
test_date_start: &test_date_start 2025-01-01
test_date_end: &test_date_end {{today}}

data_handler_config: &data_handler_config
    start_time: *train_date_start
    end_time: *test_date_end
    fit_start_time: *train_date_start
    fit_end_time: *train_date_end
    instruments: *market
    learn_processors:
        - class: DropnaLabel
          kwargs:
              fields_group: label
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
        - class: Fillna
          kwargs:
              fields_group: feature
    infer_processors:
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
        - class: Fillna
          kwargs:
              fields_group: feature
    label: ["Ref($adjclose, -5) / Ref($adjclose, -1) - 1"]
market_data_handler_config: &market_data_handler_config
    start_time: *train_date_start
    end_time: *test_date_end
    fit_start_time: *train_date_start
    fit_end_time: *train_date_end
    instruments: *market
    learn_processors:
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
        - class: Fillna
          kwargs:
              fields_group: feature
    infer_processors:
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
        - class: Fillna
          kwargs:
              fields_group: feature
port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal: <PRED>
            topk: 30
            n_drop: 3
    backtest:
        start_time: *test_date_start
        end_time: *test_date_end
        freq: day
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            deal_price: close
            limit_threshold: 0.095
            open_cost: 0.0015
            close_cost: 0.0015
            min_cost: 5
task:
    model:
        class: MASTERModel
        module_path: qlib.contrib.model.pytorch_master_ts
        kwargs:
            seed: 0
            seed_num: 5
            d_feat: 431
            d_model: 520
            gate_input_start_index: 431
            gate_input_end_index: 519
            t_nhead: 4
            s_nhead: 2
            dropout: 0.5
            n_epochs: 100
            lr: 0.00001
            train_stop_loss_thred: 0.92
            GPU: 0
            beta: 2
            market: *market
            benchmark: *benchmark
            save_prefix: *market
    dataset:
        class: MASTERTSDatasetH
        module_path: qlib.contrib.data.dataset
        kwargs:
            handler:
                class: Alpha158
                module_path: qlib.contrib.data.handler
                kwargs: *data_handler_config
            segments:
                train: [*train_date_start, *train_date_end]
                valid: [*valid_date_start, *valid_date_end]
                test: [*test_date_start, *test_date_end]
            step_len: 8
            market_data_handler_config: *market_data_handler_config
    record: 
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            config: *port_analysis_config